plugins {
    id 'com.android.application'
}


configurations.all {
    exclude group: 'org.jetbrains.kotlin'
    exclude group: 'org.jetbrains'
}

android {
    namespace 'top.misaknetwork.lockinstaller'
    compileSdk 37

    signingConfigs {
        release {
            storeFile file(System.getenv("SIGNING_KEYSTORE_PATH") ?: "release.jks")
            storePassword System.getenv("SIGNING_STORE_PASSWORD")
            keyAlias System.getenv("SIGNING_KEY_ALIAS")
            keyPassword System.getenv("SIGNING_KEY_PASSWORD")
        }
    }

    defaultConfig {
        applicationId "top.misaknetwork.lockinstaller"
        minSdk 29
        targetSdk 37
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false       
            shrinkResources false      
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }   

   
    lint {
        checkReleaseBuilds false
        abortOnError false
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    packaging {
    resources {
        excludes += [
            'META-INF/MANIFEST.MF',
            'META-INF/*.version',
            'META-INF/androidx.*',
            'META-INF/com/**',
            'META-INF/com/android/build/gradle/app-metadata.properties',
            'META-INF/version-control-info.textproto',
            'META-INF/*.kotlin_module'
        ]
    }
}
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0@aar'
    implementation 'com.android.support:support-core-utils:28.0.0'
}